Feature/pokemon
Sbusta/Angular-project pull request #1
Opened 2021-04-16 22:18 UTC by Sbusta

angular app

2021-04-19 16:08 UTC, hackeo1 requested changes
- add spaces after colon and commas
- use single quotes in ts files
- add space before {
- remove unit tests if they don't work
- indentation in ts and css files should be 2 spaces
- template must use double quotes for attributes
- avoid the use of % for paddings and margins

2021-04-19 16:08 UTC, hackeo1 commented on src/app/app.component.css
> +.mat-simple-snackbar{
space before {

2021-04-19 16:08 UTC, hackeo1 commented on src/app/app.component.ts
> +  title = 'angular-pokemon';
remove unused variables

2021-04-19 16:08 UTC, hackeo1 commented on src/app/app.module.ts
> +    StoreDevtoolsModule.instrument({ name:'Talos',maxAge: 25, logOnly: environment.production }),
space after ,

2021-04-19 16:08 UTC, hackeo1 commented on src/app/core/localstore.service.ts
> +import { Favorite } from "../shared/models/pokemon.model";
use single quote in ts files

2021-04-19 16:08 UTC, hackeo1 commented on src/app/core/localstore.service.ts
> +                                  {path: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png", name:'squirtle'}];
use single quote

2021-04-19 16:08 UTC, hackeo1 commented on src/app/core/localstore.service.ts
> +    localStorage.setItem('favorites',JSON.stringify(this.initialFavorites))
doesn't this override on every reload?

2021-04-19 16:08 UTC, hackeo1 commented on src/app/core/localstore.service.ts
> +    localStorage.setItem('favorites',JSON.stringify(this.initialFavorites))
space after ,

2021-04-19 16:08 UTC, hackeo1 commented on src/app/core/localstore.service.ts
> +    let index = temporalFavorites.findIndex((x:Favorite) => x.name === name);
don't use single character variables

2021-04-19 16:08 UTC, hackeo1 commented on src/app/core/pokemons.service.ts
> +      tap(data => console.log('data',data)),
remove unnecesary logs

2021-04-19 16:08 UTC, hackeo1 commented on src/app/core/pokemons.service.ts
> +      tap(data => console.log('data',data)),
or add a configuration to disable them

2021-04-19 16:08 UTC, hackeo1 commented on src/app/home/home.component.css
> +  font-size: 1.5rem;
use variables

2021-04-19 16:08 UTC, hackeo1 commented on src/app/home/home.component.html
> +    <img class="pokemon-img"  src="{{item.path}}">
don't use interpolation ({{}}) use input instead

2021-04-19 16:08 UTC, hackeo1 commented on src/app/home/home.component.ts
> +
remove extra lines, only one is required at the end

2021-04-19 16:08 UTC, hackeo1 commented on src/app/home/home.component.ts
> +  }
remove unused functions

2021-04-19 16:08 UTC, hackeo1 commented on src/app/material/material.module.ts
> +import {MatCardModule} from '@angular/material/card';
add line after imports

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/chart/chart.component.html
> +    <div style="display: block">
don't use inline styles

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/chart/chart.component.ts
> +              }] },
fix indentation

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/chart/chart.component.ts
> +  @Input() stats:ChartDataSets[]=[{ data: [65, 59, 80, 81, 56, 55, 40], label: 'Series A' }];
add spaces

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/chart/chart.component.ts
> +  }
remove unused functions

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/chart/chart.component.ts
> +  }
remove loggers

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/compare/compare.component.css
> +
remove extra line

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/compare/compare.component.css
> +  width: 25vw;
avoid the use of vw to give width, how does this look on mobile?

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/compare/compare.component.html
> +        {{pokemonB.weight/10}} m
avoid the use of calculations inside interpolation, they are done every time it renders

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/compare/compare.component.ts
> +      [{base_stat: 0 },{base_stat: 0},{base_stat: 0},{base_stat: 0},{base_stat: 0},{base_stat: 0}]};
improve indentation, use a constant to initialize the values

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/details/details.component.css
> +  background-color: yellow;
don't use named colors

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/details/details.component.css
> +  .description-container-list ul{
avoid the use of tags for styling

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/details/details.component.html
> +            {{pokemon.weight/10}}kg
don't add calculations in interpolations

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/details/details.component.ts
> +  isFavorite:boolean= false;
space missing

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/details/details.component.ts
> +  pokemonA:Stats={name: '', height: 0, weight: 0, sprites: {front_default:''}, abilities: [{ability:{name:''}}], types: [{type:{name:''}}], stats:
check indentation and spaces

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/details/details.component.ts
> +    let containsName = fav.some( (favorite:Favorite) => favorite.name === name)
is fav a list? use more descriptive names

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/details/details.component.ts
> +    let obj = this.description.flavor_text_entries.find((element: any) => element.language.name === 'en');
don't use any

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/pokemoncard/pokemoncard.component.ts
> +  }
use new lines to organize code, the previous code is also missing spaces

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/pokemonlist/pokemonlist.component.css
> +  color: blue;
don't use named colors

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/pokemonlist/pokemonlist.component.html
> +        <img src="../../assets/simple_pokeball.gif" alt="pokeball-gif" class="pokeball-gif">
don't use relative paths for resources

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/pokemonlist/pokemonlist.component.ts
> +    event.map((inter) => {
is this an event? it looks like it is an array of entries

2021-04-19 16:08 UTC, hackeo1 commented on src/app/pokemons/pokemonlist/pokemonlist.component.ts
> +  compare = false;
organize your class attributes in a single group

2021-04-19 16:08 UTC, hackeo1 commented on src/app/shared/format-img-url.pipe.ts
> +  imageUrl = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/';
urls should be centralized

2021-05-20 18:27 UTC, hackeo1 requested changes
I'm not able to see the file changes, it looks like there is a problem with the PR

2021-05-20 19:43 UTC, Sbusta commented
> I'm not able to see the file changes, it looks like there is a problem with the PR

humm, maybe closing the PR and open another one?

2021-05-31 15:17 UTC, closed without merging